### ISSUE TITLE
TimeoutException in Azure WebApp

### ISSUE THREAD

**Issue by holger92** [hgupta9/FluentFTP#71]
Hi,
I use FluentFTP in an Azure WebApp and I get frequently a TimeoutException (Timed out trying to connect.) I contacted the Azure support but they said on WebApp side everything looks good. 
I have a test function that simulates our use case.
```csharp
public string TestFtpClient(int number)
{
	string files = "";
	for (var i = 0; i < number; i++)
	{
		var _client = new FtpClient();
		_client.Host = "ftp.server.de";
		_client.Credentials = new System.Net.NetworkCredential("user", "pw");
		_client.DataConnectionType = FtpDataConnectionType.PASV;
		_client.Connect();

		var listings = _client.GetListing("./test/");
		foreach (var listing in listings)
		{
			files += listing.Name + "  ";
		}
		files += "----------------------";
		_client.Disconnect();
		_client.Dispose();
	}
	return files;
}
```
If I call the function with `int number = 3` everything works pretty good. But if I call the function again right after I get the result I get the TimeoutException. I get also the Exception if `int number` is about 10 or greater.

Here is the whole exception:
```json
{"message":"An error has occurred.","exceptionMessage":"Timed out trying to connect!","exceptionType":"System.TimeoutException","stackTrace":"   at System.Net.FtpClient.FtpSocketStream.Connect(String host, Int32 port, FtpIpVersion ipVersions)\r\n   at System.Net.FtpClient.FtpClient.OpenPassiveDataStream(FtpDataConnectionType type, String command, Int64 restart)\r\n   at System.Net.FtpClient.FtpClient.OpenDataStream(String command, Int64 restart)\r\n   at System.Net.FtpClient.FtpClient.GetNameListing(String path)\r\n   at Dennree.Bibliothek.WebApi.Controllers.FtpTestController.TesteFtpClient(Int32 anzahl)\r\n   at lambda_method(Closure , Object , Object[] )\r\n   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.<>c__DisplayClass10.<GetExecutor>b__9(Object instance, Object[] methodParameters)\r\n   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.Execute(Object instance, Object[] arguments)\r\n   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ExecuteAsync(HttpControllerContext controllerContext, IDictionary`2 arguments, CancellationToken cancellationToken)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__0.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__5.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__5.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Filters.ActionFilterAttribute.<ExecuteActionFilterAsyncCore>d__0.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__5.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__5.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Filters.ActionFilterAttribute.<ExecuteActionFilterAsyncCore>d__0.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__2.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Filters.AuthorizationFilterAttribute.<ExecuteAuthorizationFilterAsyncCore>d__2.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Controllers.ExceptionFilterResult.<ExecuteAsync>d__0.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Web.Http.Controllers.ExceptionFilterResult.<ExecuteAsync>d__0.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Dispatcher.HttpControllerDispatcher.<SendAsync>d__1.MoveNext()"}
```

If I just call `Connect();`, `Disconnect();`, and `Dispose();` there is no exception. So the exception occurs when I try to get the listing. The Azure support was thinking about a leak of ports.

I can't reproduce the issue on my local machine.
Could this be a problem of the ftp client or should i look deeper into Azure?

Thanks,
Holger

**Comment by hgupta9** [comment]
Its a complicated problem. Try adding a delay of 1 sec or 10 secs after each Dispose() and see if that works for you? Other people seem to be getting this problem too (I just did a google for "ftp azure timeout")
- https://social.msdn.microsoft.com/Forums/azure/en-US/a7c025f9-6740-47be-9ae6-0c1019cea893/ftp-to-azure-website-is-very-slow-timeout-all-the-times-please-help-thanks?forum=windowsazurewebsitespreview
- https://social.msdn.microsoft.com/Forums/azure/en-US/96e27c8b-54cf-4629-9e1c-fe1acde94c5f/timeouts-and-connection-problems-when-using-ftps-upload-to-azure?forum=windowsazurewebsitespreview
- http://serverfault.com/questions/524926/cannot-use-ftp-passive-mode-after-recent-windows-azure-vm-maintenance

Do any of those links help? I tried going into it but did not have the time to look deeply into the matter.

**Comment by holger92** [comment]
Thanks for the quick response. Adding a delay does not solve the problem. I googled a lot but the most links are about ftp and deploy purposes or ftp to/from an azure VM.
I try to up- and download to/from our ftp server with a C# application hosted in azure.

I edited my test function to get the listing via FtpWebRequest and there is no exception anymore. Maybe this could help.

**Comment by hgupta9** [comment]
Could you share the code that worked for you so I could analyze what was different?

**Comment by holger92** [comment]
Here is the code:
```
[AllowAnonymous]
public List<string> TestFtpListing()
{
	FtpWebRequest ftpRequest = (FtpWebRequest)WebRequest.Create("ftp://ftp.server.de/dir/dir/dir/");
	ftpRequest.Credentials = new NetworkCredential("user", "passwd");
	ftpRequest.Method = WebRequestMethods.Ftp.ListDirectory;
	FtpWebResponse response = (FtpWebResponse)ftpRequest.GetResponse();
	StreamReader streamReader = new StreamReader(response.GetResponseStream());

	List<string> files = new List<string>();

	string line = streamReader.ReadLine();
	while (!string.IsNullOrEmpty(line))
	{
		files.Add(line);
		line = streamReader.ReadLine();
	}

	streamReader.Close();
	return files;
}

[HttpGet]
[AllowAnonymous]
public List<string> TestFtpListingFluent()
{
	var client = new FtpClient();
	client.Host = "ftp.server.de";
	client.Credentials = new NetworkCredential("user", "passwd");
	client.DataConnectionType = FtpDataConnectionType.PASV;
	client.Connect();
	var returnValue = client.GetListing("./dir/dir/dir/");
	client.Disconnect();
	client.Dispose();

	List<string> files = new List<string>();
	foreach (var item in returnValue)
	{
		files.Add(item.Name);
	}
	return files;
}
```
So if I call `TestFtpListing()` there are no problems.
`TestFtpListingFluent()` works the at the beginning but if I call the function about 4 times (refresh the site) I'll get the timeout exception.

**Comment by hgupta9** [comment]
Can you try the latest beta and see if it works for you? The GetListing() has been upgraded so if that was the issue your problem should be solved:

https://github.com/hgupta9/FluentFTP/issues/85

**Comment by holger92** [comment]
I will try it tomorrow!

**Comment by hgupta9** [comment]
Okay see if solution A or B works for you:

Solution A:
```cs
client.SocketPollInterval = 1000;
```

Solution B:
```cs
client.SocketPollInterval = 1000;
client.ConnectTimeout = 2000;
client.ReadTimeout = 2000;
client.DataConnectionConnectTimeout = 2000;
client.DataConnectionReadTimeout = 2000;
```

**Comment by holger92** [comment]
I tried both solutions but the error still occurs. So I have talked again to the services provider which manages the ftp server and we found out that Azure behaves very strange when dealing with ftp requests.
Azure sometimes changes the IP-address during a request. The connection is established with IP-address A and for the data transfer Azure uses IP-address B and this isn't allowed on many firewalls.
It isn't easy to reproduce because Azure does this not every time but it is definitely an Azure bug.

Thanks for your time and the provided solutions!

**Comment by royben** [comment]
Had the same issue when trying to download a folder from an Azure WebApp FTP.

Managed to solve it using the following settings:

        FtpClient client = new FtpClient(host, userName, password);
        client.SslProtocols = SslProtocols.Tls;
        client.ValidateAnyCertificate = true;
        client.DataConnectionType = FtpDataConnectionType.PASV;
        client.DownloadDataType = FtpDataType.Binary;
        client.RetryAttempts = 5;
        client.SocketPollInterval = 1000;
        client.ConnectTimeout = 2000;
        client.ReadTimeout = 2000;
        client.DataConnectionConnectTimeout = 2000;
        client.DataConnectionReadTimeout = 2000;

**Comment by robinrodricks** [comment]
Is there anything in the logs that will help us to identify an azure
server? Maybe the IP address or the domain name?

**Comment by royben** [comment]
I think so.

It seems that all azure web apps publish profiles FTP addresses ends with:

ftp.azurewebsites.windows.net
